#!/usr/bin/env python
# Originally from the http://www.handhelds.org/ project.
# Modified by Rich Wareham

import sys, os, string, re, time

if len(sys.argv) > 3:
    name = sys.argv[1]
    file = sys.argv[2]
    outfile = sys.argv[3]
else:
    name = 'bindata'
    file = sys.argv[1]
    outfile = sys.argv[2]

in_file = open(file, 'r')
out_file = open(outfile, 'w')

out_file.write("/*\n")
out_file.write(" *\n")
out_file.write(" * Generated by %s\n" % sys.argv[0])
out_file.write(" * on %s\n" % time.ctime(time.time()))
out_file.write(" *\n")
out_file.write(" */\n")
    
t = name
t = re.sub('\..*$', '', t)
t = re.sub('[^a-zA-Z_0-9]', '_', t)
if re.search('^[^a-zA-Z_]', t):
    t = '_' + t
out_file.write('unsigned char %s[] = {' % t,)

byte_count = 0
output = []
while 1:
    c = in_file.read(1)
    if not c:
	output.append('0x00')
        break
    if (byte_count % 8) == 0:
        output.append('\n\t')
    output.append('0x%02x,' % ord(c))
    byte_count = byte_count + 1

out_file.write(string.join(output, ''))
out_file.write('\n};\n')

sys.exit(0)
